sudo: required
services:
  - docker

before_install:
  - docker build -t architraigupta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true architraigupta/react-test npm test

after_success:
  # build all 4 docker images
  - docker build -t architraigupta/multi-client ./client
  - docker build -t architraigupta/multi-nginx ./nginx
  - docker build -t architraigupta/multi-server ./server
  - docker build -t architraigupta/multi-worker ./worker

  # Login to docer cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the docker imgaes built above and push them to docker hub
  - docker push architraigupta/multi-client
  - docker push architraigupta/multi-nginx
  - docker push architraigupta/multi-server
  - docker push architraigupta/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-947548241628'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY